
name: Publish SPARQL docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'

  pull_request:

permissions:
  contents: read

jobs:

  compile:

    name: Compile
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build using docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: rocksdb-build:latest
          file: Dockerfile.build

      - name: Compile
        run: docker run --name build rocksdb-build make librdf_storage_rocksdb.so

      - name: Extract executable
        run: docker cp build:/build/librdf_storage_rocksdb.so librdf_storage_rocksdb.so

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb-shared-library
          path: librdf_storage_rocksdb.so

  build-image:
    name: Container image
    needs: compile
    runs-on: ubuntu-latest

    steps:

     - name: Checkout
       uses: actions/checkout@v3

     - name: Download executable
       uses: actions/download-artifact@v3
       with:
         name: rocksdb-shared-library

     - name: Log in to Docker Hub
       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: cybermaggedon/sparql-service-rocksdb
         tags: |
           type=ref,event=branch
           type=ref,event=pr
           type=semver,pattern={{version}}
           type=semver,pattern={{major}}.{{minor}}

     - name: Build and push
       uses: docker/build-push-action@v3
       with:
         context: .
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}

